# application.yml (arquivo principal)
spring:
  application:
    name: compawny
  profiles:
    active: test

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true